Repository WSU-CEG-6110-4410/AirViewer, pull requests merged in 2022-04, with the labels that each got.

#8 Added changes in controller for selecting only pdf
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#34 Air viewer sireesha
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/java/edu/wright/airviewer2/AIRViewerModel.java
  src/main/java/edu/wright/airviewer2/AbstractDocumentCommandWrapper.java
Labels: enhancement, User Story

#43 Airviewer Sireesha 2 : Code changes for issue 15.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: User Story, Task

#44 Added code coverage reports, program by contract, SDD
  SDD.zip
  codecoverage/ProgressBarAndIndicator.pdf
  codecoverage/SplitAndMerge.pdf
  codecoverage/ZoomInZoomOut.pdf
  codecoverage/jacoco.zip
  program by contract.txt
Labels: documentation

#45 Air viewer sireesha 2 to master for issue 28
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: User Story, Task

#46 AirViewer-Sireesha-2: added unit test cases issue#5
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/test/java/edu/wright/airviewer2/AirViewerControllerTest.java
Labels: User Story, Task

#47 Airviewer-Sireesha-2:issue 14, program by contract doxygen changes
  Literate Programming Document Sireesha.txt
  Programing by Contract Sireesha.txt
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/java/edu/wright/airviewer2/AIRViewerModel.java
Labels: User Story, Task

#48 Doxygen changes added
  Doxygen Sireesha.zip
Labels: User Story, Task
